name: Coding and Cocktails workflow
run-name: Make cocktails ğŸš€

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  make_cocktails:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Add Ice
      run: echo "ğŸ§Š Add ice to the mixing glass or cocktail shaker"
      shell: bash

    - name: Mix Ingredients
      run: echo "ğŸ‰ Mix the ingredients"
      shell: bash

    - name: Poor Ingredients
      run: echo "ğŸ¸ Poor the mixed ingredients into the cocktail serving glass"
      shell: bash

    - name: Add Garnish
      run: echo "ğŸ€ Add the garnish to the serving glass"
      shell: bash
